services:
  bdd:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MARIADB_DATABASE: ${MYSQL_DATABASE}
      MARIADB_USER: ${MYSQL_USER}
      MARIADB_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - expernetResa

  api:
    build:
      context: ./backend
    container_name: api
    restart: always
    environment:
      MYSQL_HOST: bdd
      MYSQL_PORT: 3306
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      NODE_ENV: production
    depends_on:
      - bdd
    networks:
      - expernetResa

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "8080:80"  # Frontend accessible sur http://localhost:8080
    depends_on:
      - api
    networks:
      - expernetResa

networks:
  expernetResa:
    driver: bridge

volumes:
  db_data:
