services:
  bdd:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MARIADB_DATABASE: ${MYSQL_DATABASE}
      MARIADB_USER: ${MYSQL_USER}
      MARIADB_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - expernetResa

  api:
    build:
      context: ./backend
    container_name: api
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules 
    environment:
      MYSQL_HOST: bdd
      MYSQL_PORT: 3306
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    depends_on:
      - bdd
    networks:
      - expernetResa

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - api
    networks:
      - expernetResa
    volumes:
      - ./frontend:/usr/share/nginx/html


networks:
  expernetResa:
    driver: bridge

volumes:
  db_data:
