name: Run Tests

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.19.5

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: NODE_ENV=test NODE_OPTIONS=--experimental-vm-modules npm test
